name: Generate QR Codes

on:
  schedule:
    - cron: "0 3 * * *"   # tous les jours à 03h (UTC)
  workflow_dispatch:       # permet de lancer à la main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup PowerShell
      uses: actions/setup-powershell@v2

    - name: Run QR code generation
      shell: pwsh
      run: |
        ./scripts/Global.ps1 `

    - name: Commit & push if changes
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add .
        if (git status --porcelain) {
          git commit -m "Auto update QR codes"
          git push
        }
